export const NOTIFICATION_JOBS = {
  NEW_MESSAGE: "NEW_MESSAGE",
  NEW_POST: "NEW_POST",
  FOLLOW_REQUEST: "FOLLOW_REQUEST",
  FOLLOW_ACCEPTED: "FOLLOW_ACCEPTED",
  POST_LIKE: "POST_LIKE",
  POST_COMMENT: "POST_COMMENT",
  MENTION: "MENTION"
};